from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol

from .project import ProjectRecord


class ProjectStore(Protocol):
    async def create(self, project: ProjectRecord) -> None: ...

    async def get(self, project_id: str) -> ProjectRecord | None: ...

    async def list(self) -> Sequence[ProjectRecord]: ...

    async def update(self, project: ProjectRecord) -> None: ...

    async def get_active(self) -> ProjectRecord | None: ...

    async def set_active(self, project_id: str) -> ProjectRecord: ...

    async def reset_state(self, project_id: str) -> ProjectRecord: ...

    async def delete(self, project_id: str) -> bool: ...
